;********** DELARRYV.INC - variables for CWDelArray routine
;
;Copyright  (c)1992 Fred Sexton Jr.
ary_id       TEXTEQU  <WORD PTR ds:[45962]>
CW_hand      TEXTEQU  <WORD PTR ds:[45964]>

this_r_hdrl  TEXTEQU  <WORD PTR ds:[45966]>
this_r_hdrh  TEXTEQU  <WORD PTR ds:[45968]>

asize_l      TEXTEQU  <WORD PTR ds:[45970]>
asize_h      TEXTEQU  <WORD PTR ds:[45972]>
this_w_hdrl  TEXTEQU  <WORD PTR ds:[45974]>
this_w_hdrh  TEXTEQU  <WORD PTR ds:[45976]>
nxt_r_hdrl   TEXTEQU  <WORD PTR ds:[45978]>

nxt_r_hdrh   TEXTEQU  <WORD PTR ds:[45980]>
prev_r_hdrl  TEXTEQU  <WORD PTR ds:[45982]>
prev_r_hdrh  TEXTEQU  <WORD PTR ds:[45984]>
prev_w_hdrl  TEXTEQU  <WORD PTR ds:[45986]>
prev_w_hdrh  TEXTEQU  <WORD PTR ds:[45988]>

fs_mode      TEXTEQU  <WORD PTR ds:[45990]>
tmp_var1     TEXTEQU  <WORD PTR ds:[45992]>
tmp_var2     TEXTEQU  <WORD PTR ds:[45994]>
tmp_var3     TEXTEQU  <WORD PTR ds:[45996]>
tmp_var4     TEXTEQU  <WORD PTR ds:[45998]>

vari_loc     TEXTEQU  <45960>
tmpv_loc     TEXTEQU  <45992>
thdr_loc     TEXTEQU  <45974>
cwfn_copy    TEXTEQU  <45814>
