;********** DELFILEV.INC - variables for CWDelFile
;
;Copyright (c) 1992 Fred Sexton Jr.

CW_hand	     TEXTEQU  <WORD PTR ds:[55962]>
cmpr_len     TEXTEQU  <WORD PTR ds:[55964]>
this_r_hdrl  TEXTEQU  <WORD PTR ds:[55966]>
this_r_hdrh  TEXTEQU  <WORD PTR ds:[55968]>

fsize_decl   TEXTEQU  <WORD PTR ds:[55970]>
fsize_dech   TEXTEQU  <WORD PTR ds:[55972]>
this_w_hdrl  TEXTEQU  <WORD PTR ds:[55974]>
this_w_hdrh  TEXTEQU  <WORD PTR ds:[55976]>
nxt_r_hdrl   TEXTEQU  <WORD PTR ds:[55978]>

nxt_r_hdrh   TEXTEQU  <WORD PTR ds:[55980]>
prev_r_hdrl  TEXTEQU  <WORD PTR ds:[55982]>
prev_r_hdrh  TEXTEQU  <WORD PTR ds:[55984]>
prev_w_hdrl  TEXTEQU  <WORD PTR ds:[55986]>
prev_w_hdrh  TEXTEQU  <WORD PTR ds:[55988]>

fs_mode      TEXTEQU  <WORD PTR ds:[55990]>
tmp_var1     TEXTEQU  <WORD PTR ds:[55992]>
tmp_var2     TEXTEQU  <WORD PTR ds:[55994]>
tmp_var3     TEXTEQU  <WORD PTR ds:[55996]>
tmp_var4     TEXTEQU  <WORD PTR ds:[55998]>

vari_loc     TEXTEQU  <55960>
tmpv_loc     TEXTEQU  <55992>
thdr_loc     TEXTEQU  <55974>
CWfn_copy    TEXTEQU  <55814>
cmpr_loc     TEXTEQU  <55948>
