;********** PCKARYMV.INC - variables for CWPackArrayM
;
;Copyright (c) 1992 Fred Sexton Jr.

stor_loc     TEXTEQU  <WORD PTR ds:[45962]>
tm_seg_fix   TEXTEQU  <WORD PTR ds:[45964]>
tmem_seg     TEXTEQU  <WORD PTR ds:[45966]>
max_outl     TEXTEQU  <WORD PTR ds:[45968]>

max_outh     TEXTEQU  <WORD PTR ds:[45970]>
asize_l      TEXTEQU  <WORD PTR ds:[45972]>
asize_h      TEXTEQU  <WORD PTR ds:[45974]>
i_buff_ptr   TEXTEQU  <WORD PTR ds:[45976]>
o_buff_ptr   TEXTEQU  <WORD PTR ds:[45978]>

hold_val     TEXTEQU  <WORD PTR ds:[45980]>
t_loc        TEXTEQU  <WORD PTR ds:[45982]>
in_val       TEXTEQU  <BYTE PTR ds:[45984]>
total_l      TEXTEQU  <WORD PTR ds:[45986]>
total_h      TEXTEQU  <WORD PTR ds:[45988]>

tmp_var1     TEXTEQU  <WORD PTR ds:[45990]>
tmp_var2     TEXTEQU  <WORD PTR ds:[45992]>
tmp_var3     TEXTEQU  <WORD PTR ds:[45994]>
tmp_var4     TEXTEQU  <WORD PTR ds:[45996]>
tmp_var5     TEXTEQU  <WORD PTR ds:[45998]>

o_buff_loc   TEXTEQU  <45145>
vari_loc     TEXTEQU  <45958>
tmpv_loc     TEXTEQU  <45990>
