;********** UPCKARMV.INC - variables for CWUnpackArrayM
;
;Copyright (c) 1992 Fred Sexton Jr.

nxt_cd_loc   TEXTEQU <WORD PTR ds:[45968]>
tm_seg_fix   TEXTEQU <WORD PTR ds:[45970]>
tmem_seg     TEXTEQU <WORD PTR ds:[45972]>

t_loc        TEXTEQU <WORD PTR ds:[45974]>
i_buff_ptr   TEXTEQU <WORD PTR ds:[45976]>
i_buff_count TEXTEQU <WORD PTR ds:[45978]>

op_ptr       TEXTEQU <WORD PTR ds:[45980]>
o_stk_count  TEXTEQU <WORD PTR ds:[45982]>
o_stk_ptr    TEXTEQU <WORD PTR ds:[45984]>
asize_l      TEXTEQU <WORD PTR ds:[45986]>
asize_h      TEXTEQU <WORD PTR ds:[45988]>

tmp_var1     TEXTEQU <WORD PTR ds:[45990]>
tmp_var2     TEXTEQU <WORD PTR ds:[45992]>
tmp_var3     TEXTEQU <WORD PTR ds:[45994]>
tmp_var4     TEXTEQU <WORD PTR ds:[45996]>
tmp_var5     TEXTEQU <WORD PTR ds:[45998]>

suf_loc      TEXTEQU <16384>
o_stk_loc    TEXTEQU <24576>
vari_loc     TEXTEQU <45958>
