;********** UPCKARYV.INC - variables for CWUnpackArray
;
;Copyright (c) 1992 Fred Sexton Jr.

s_hand       TEXTEQU <WORD PTR ds:[45980]>
stor_done    TEXTEQU <WORD PTR ds:[45982]>
t_loc        TEXTEQU <WORD PTR ds:[45984]>
i_buff_ptr   TEXTEQU <WORD PTR ds:[45986]>
i_buff_count TEXTEQU <WORD PTR ds:[45988]>

op_ptr       TEXTEQU <WORD PTR ds:[45990]>
o_stk_count  TEXTEQU <WORD PTR ds:[45992]>
o_stk_ptr    TEXTEQU <WORD PTR ds:[45994]>
asize_l      TEXTEQU <WORD PTR ds:[45996]>
asize_h      TEXTEQU <WORD PTR ds:[45998]>

suf_loc      TEXTEQU <16384>
o_stk_loc    TEXTEQU <24576>
vari_loc     TEXTEQU <45980>
